# Generated by Django 4.1.7 on 2023-03-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_precioconsulta_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='horario',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='horario_entrada',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='horario_salida',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_dias', to='Gestion.medico')),
            ],
            options={
                'verbose_name': 'Horario de Día',
                'verbose_name_plural': 'Horarios de Días',
                'unique_together': {('medico', 'dia')},
            },
        ),
    ]
