# Generated by Django 4.1.7 on 2023-03-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_remove_medico_horario_remove_secretaria_horario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
